---
# Configuration to start up a database container (mariadb, mysql or mongodb) for use developing
# a database for Cynthia Hurley Wines.
# There's no dependency between these services, it was just more convenient to have them all in
# a single compose file, and bring them up and down individually.

version: '3.7'
services:
  chw-mariadb:
    image: docker.io/library/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: finewine
      MARIADB_USER: chwuser
      MARIADB_PASSWORD: cynthiahurley
      MARIADB_DATABASE: chw
    ports:
      - '3306:3306'
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./data/infiles:/tmp/data/infiles

  chw-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: finewine
      MYSQL_USER: chwuser
      MYSQL_PASSWORD: cynthiahurley
      MYSQL_DATABASE: chw
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/infiles:/tmp/data/infiles

  chw-mongo:
    image: mongo:${MONGO_VER-latest}
    ports:
      - '27017:27017'
    volumes:
      - chw-mongo-data:/data/db
      - chw-mongo-configdb:/data/configdb

volumes:
  chw-mongo-data:
  chw-mongo-configdb:
  chw-mysql-retailorders-data:
  chw-mariadb-retailorders-data:
