LOAD DATA LOCAL INFILE '/tmp/data/infiles/WineMasterTable_09-23-3.csv'
REPLACE INTO TABLE LegacyWineMaster_923
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES
(
WineId,
AccountingItemNo,
NYPPItemNo,
WesternItemNo,
COLA_TTBID,
UPC,
FullName,
@Vintage,
Color,
StillSparklingFortified,
CertifiedOrganic,
Varietals,
@ABV,
Country,
Region,
SubRegion,
Appellation,
CaseUnitType,
BottleSize,
BottlesPerCase,
BottleColor,
FrontLabelFilename,
BackLabelFilename,
ShelfTalkerText,
TastingNotes,
Vinification,
TerroirVineyardPractices,
PressParagraph,
ProducerName,
ProducerDescription,
ProducerCode,
YearEstablished,
COLA_PDF_Filename,
NJ_AssignedUPC,
NJ_BrandRegNo,
@CREATED,
@LASTUPDATED,
Excluded,
SoldOut,
PriceListSection,
PriceListNotes,
@FOBPrice,
FOB_ARB,
@NY_PP,
@NY_MultiCasePrice,
@NY_MultiCaseQty,
@NJ_PP,
@NJ_MultiCasePrice,
@NJ_MultiCaseQty,
NY_CurrentPricing,
NJ_CurrentPricing
)
SET
Vintage=if(@Vintage = 'NV', -1, @Vintage),
ABV=if(@ABV = '', NULL, @ABV),
DateCreated=if(@CREATED = '', NULL, @CREATED),
LastUpdated=if(@LASTUPDATED = '', NULL, @LASTUPDATED),
FOBPrice=if(@FOBPrice = '', NULL, @FOBPrice),
NY_PP=if(@NY_PP = '', NULL, @NY_PP),
NY_MultiCasePrice=if(@NY_MultiCasePrice = '', NULL, @NY_MultiCasePrice),
NY_MultiCaseQty=if(@NY_MultiCaseQty = '', NULL, @NY_MultiCaseQty),
NJ_PP=if(@NJ_PP = '', NULL, @NJ_PP),
NJ_MultiCasePrice=if(@NJ_MultiCasePrice = '', NULL, @NJ_MultiCasePrice),
NJ_MultiCaseQty=if(@NJ_MultiCaseQty = '', NULL, @NJ_MultiCaseQty);

CREATE TABLE LegacyWineMaster_923 (
                WineId INT NOT NULL,
                AccountingItemNo VARCHAR(11),
                NYPPItemNo VARCHAR(17),
                WesternItemNo VARCHAR(11),
                COLA_TTBID VARCHAR(15),
                UPC VARCHAR(13),
                FullName VARCHAR(114) NOT NULL,
                Vintage SMALLINT,
                Color VARCHAR(5),
                StillSparklingFortified VARCHAR(9),
                CertifiedOrganic VARCHAR(19),
                Varietals VARCHAR(100),
                ABV DECIMAL(5,2),
                Country VARCHAR(7),
                Region VARCHAR(20),
                SubRegion VARCHAR(20),
                Appellation VARCHAR(58),
                CaseUnitType VARCHAR(7),
                BottleSize VARCHAR(18),
                BottlesPerCase TINYINT,
                BottleColor VARCHAR(6),
                FrontLabelFilename VARCHAR(86),
                BackLabelFilename VARCHAR(53),
                ShelfTalkerText TEXT(1030),
                TastingNotes TEXT(1248),
                Vinification TEXT(1146),
                TerroirVineyardPractices TEXT(1359),
                PressParagraph TEXT(4660),
                ProducerName VARCHAR(58),
                ProducerDescription TEXT(1269),
                ProducerCode CHAR(3),
                YearEstablished VARCHAR(27),
                COLA_PDF_Filename VARCHAR(70),
                NJ_AssignedUPC VARCHAR(13),
                NJ_BrandRegNo VARCHAR(6),
                DateCreated DATE,
                LastUpdated DATETIME,
                Excluded VARCHAR(24),
                SoldOut CHAR(1),
                PriceListSection VARCHAR(39),
                PriceListNotes VARCHAR(144),
                FOBPrice DECIMAL(8,2),
                FOB_ARB VARCHAR(29),
                NY_PP DECIMAL(8,2),
                NY_MultiCasePrice DECIMAL(8,2),
                NY_MultiCaseQty TINYINT,
                NJ_PP DECIMAL(8,2),
                NJ_MultiCasePrice DECIMAL(8,2),
                NJ_MultiCaseQty TINYINT,
                NY_CurrentPricing VARCHAR(42),
                NJ_CurrentPricing VARCHAR(30),
                PRIMARY KEY (WineId)
);

SELECT
WineId,
AccountingItemNo,
NY_CurrentPricing,
NY_PP,
NY_MultiCasePrice,
NY_MultiCaseQty,
NJ_CurrentPricing,
NJ_PP,
NJ_MultiCasePrice,
NJ_MultiCaseQty
FROM LegacyWineMaster_923
INTO OUTFILE '/tmp/data/infiles/WinePricing_09-23.tsv'
;

/* To get permission to write to a file execute the following SQL statement AS the root user: */
GRANT FILE ON *.* TO chwuser;

# Some vim macros for fixing the csv written by libreoffice Calc
:%s/^$/\\n/
:%s/\\n\n/\\n\\n/
:%s/\n\\n/\\n\\n/
:%s/\n"|/\\n"|/
:%s/\n\([^0-9][^0-9][^0-9][^0-9][^|]\)/\\n\1/
:%s/|"""/|"\\"/g
:%s/""/\\"/g

# fix LastUpdated date mm/dd/yyyy -> yyyy-mm-dd
:%s,|\(\d\{2}\)/\(\d\{2}\)/\(\d\{4}\) ,|\3-\1-\2 ,


LOAD DATA LOCAL INFILE '/tmp/data/infiles/EmailWineOrders_09-11-cleaned.csv'
REPLACE INTO TABLE LegacyEmailOrders_911
FIELDS TERMINATED BY '|' OPTIONALLY ENCLOSED BY '"'
IGNORE 1 LINES
(
EmailOrderId,
@FirstDate,
@InqDate,
FullName,
LastName,
CompanyAptNo,
Street,
City,
State,
Zip,
PhoneHome,
PhoneWork,
FaxNumber,
Email,
Email1,
Source,
SubPaid,
CCVisa,
CCAmex,
CCMastercard,
CC_ID,
TotalRetailCharge,
Fax,
Quantity,
Quant2,
Quant3,
Quant4,
Quant5,
DelItemss,
DelItem2,
DelItem3,
DelItem4,
DelItem5,
@Vintage,
@Vintage2,
@Vintage3,
@Vintage4,
@Vintage5,
CustDetails
)
SET
FirstDate=if(LENGTH(@FirstDate) < 9, NULL, @FirstDate),
InqDate=if(LENGTH(@InqDate) < 9, NULL, @InqDate),
Vintage=if(@Vintage REGEXP '^[0-9]{4}$', @Vintage, NULL),
Vintage2=if(@Vintage2 REGEXP '^[0-9]{4}$', @Vintage2, NULL),
Vintage3=if(@Vintage3 REGEXP '^[0-9]{4}$', @Vintage3, NULL),
Vintage4=if(@Vintage4 REGEXP '^[0-9]{4}$', @Vintage4, NULL),
Vintage5=if(@Vintage5 REGEXP '^[0-9]{4}$', @Vintage5, NULL)
;

CREATE TABLE LegacyEmailOrders_911 (
                EmailOrderId INT NOT NULL,
                FirstDate DATE,
                InqDate DATE,
                FullName VARCHAR(69),
                LastName VARCHAR(26),
                CompanyAptNo VARCHAR(56),
                Street VARCHAR(102),
                City VARCHAR(39),
                State VARCHAR(14),
                Zip VARCHAR(14),
                PhoneHome VARCHAR(44),
                PhoneWork VARCHAR(30),
                FaxNumber VARCHAR(22),
                Email TEXT(965),
                Email1 TEXT(490),
                Source VARCHAR(38),
                SubPaid VARCHAR(23),
                CCVisa VARCHAR(61),
                CCAmex VARCHAR(90),
                CCMastercard VARCHAR(81),
                CC_ID VARCHAR(39),
                TotalRetailCharge VARCHAR(101),
                Fax VARCHAR(33),
                Quantity VARCHAR(37),
                Quant2 VARCHAR(24),
                Quant3 VARCHAR(34),
                Quant4 VARCHAR(36),
                Quant5 VARCHAR(22),
                DelItemss VARCHAR(88),
                DelItem2 TEXT(2089),
                DelItem3 VARCHAR(71),
                DelItem4 VARCHAR(73),
                DelItem5 VARCHAR(71),
                Vintage SMALLINT,
                Vintage2 SMALLINT,
                Vintage3 SMALLINT,
                Vintage4 SMALLINT,
                Vintage5 SMALLINT,
                CustDetails TEXT(1065),
                PRIMARY KEY (EmailOrderId)
);
